### ISSUE TITLE
java.lang.NoClassDefFoundError: com.parse.ParseFacebookUtils$1 persistent error

### ISSUE THREAD

**Issue by JulianoEngineer** [ParsePlatform/ParseFacebookUtils-Android#18]
At [Issue #12 ](https://github.com/ParsePlatform/ParseFacebookUtils-Android/issues/12) apparently the solution for this problem was found. But following the instructions i don't find the same result, and the error using ```ParseFacebookUtils.initialize()``` continues to throwing the error. Please provides the correct gradle dependencies for solve this problem. I'm using:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile project(':facebook')
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'com.google.android.gms:play-services-ads:8.3.0'
    compile 'com.parse:parsefacebookutils-v4-android:1.10.4@aar'
    //compile fileTree(dir: 'libs', include: 'Parse-*.jar')
```

**Comment by grantland** [comment]
1. What's in your `/libs` folder?
2. Is your local `:facebook` module required?
3. What's your gradle build output?

**Comment by rejish4gt** [comment]
The reason why you get the error is because the dependencies for parsefacebookutils isn't being pulled on build so you'd have to add it manually. parsefacebookutils depends on facebooksdk and parse-android. Add the following code into your gradle and it should work fine. 

`dependencies {
...
    compile 'com.parse:parse-android:1.13.0'
    compile 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'
    compile 'com.facebook.android:facebook-android-sdk:4.9.0'
...
}`

**Comment by liquiddandruff** [comment]
I get this error too on the sample project when trying to launch ParseLoginSampleBasic. The other builds like ParseLoginSampleWithDispatchActivity work fine though.

Stack trace

```
                                                                         --------- beginning of crash
02-15 00:04:37.950 303-303/com.parse.loginsample.basic E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.parse.loginsample.basic, PID: 303
                                                                         java.lang.NoClassDefFoundError: Failed resolution of: Lcom/parse/Parse;
                                                                             at com.parse.loginsample.basic.SampleApplication.onCreate(SampleApplication.java:35)
                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
....
```
