### ISSUE TITLE
linkWithReadPermissionsInBackground callback is never called

### ISSUE THREAD

**Issue by miav** [ParsePlatform/ParseFacebookUtils-Android#19]
I am doing something like:

```
ParseFacebookUtils.linkWithReadPermissionsInBackground(ParseUser.getCurrentUser(),
                getActivity(), permissions, new SaveCallback() {
                    @Override
                    public void done(ParseException e) {
                        if (e != null || !ParseUserUtils.isLinkedWithFacebook()) {
                           App.toast(getActivity(), "Something went wrong!”);
                        } else {
                           App.toast(getActivity(), "Successfully linked”);
                        }
                   }
               });
```

but `done()` is never called. I see no toast and my breakpoints are not reached. I have verified through the dashboard (and with subsequent logins) that the user **is getting linked**, but simply `done()` is never called. Same with bolts continuations.

At first I thought it was just a very long operation. In that case it would be reasonable to throw a "request timed out” exception after a while. But actually on the dashboard I can see that the operation ends (either successfully or not).

**Comment by grantland** [comment]
Could you post all relevant bits of your Activity/Fragment?

**Comment by miav** [comment]
@grantland hard to say what’s relevant...? The activity is the main activity of a pretty complete application. The fragment from which I am calling this is just a place where the user can manage its data. I am pretty sure that when the code above is fired nothing else is running.

The code above is fired on clicking a button, which does nothing else. I can wait for minutes but done is not called. If I re-click the button, I get [this exception](https://github.com/ParsePlatform/ParseFacebookUtils-Android/blob/master/library/src/main/java/com/parse/FacebookController.java#L91)

Tell me if I can give you more info.

**Comment by grantland** [comment]
Relevant bits would be calls to `ParseFacebookUtils.onActivityResult(...)` as documented here: http://parse.com/docs/android/api/com/parse/ParseFacebookUtils.html

**Comment by miav** [comment]
You are right sir, I was doing something wrong there. Thank you.

**Comment by sanergulec** [comment]
Hello miav I have the exact same issue, how did you solved it? My code is as below:

```
                List<String> permissions = Arrays.asList("public_profile", "email", "user_friends");

                System.out.println("I am here 2");

                if (!ParseFacebookUtils.isLinked(ParseUser.getCurrentUser())) {

                    System.out.println("I am here 3");
                    ParseFacebookUtils.linkWithReadPermissionsInBackground(ParseUser.getCurrentUser(), this, permissions, new SaveCallback() {
                        @Override
                        public void done(ParseException ex) {
                            System.out.println("I am here 4");
                            if (ParseFacebookUtils.isLinked(ParseUser.getCurrentUser())) {
                                Log.d("MyApp", "Woohoo, user logged in with Facebook!");

                            }

                            else {

                                Log.e("MyLast", "unexpected error of mine", ex);


                            }

                        }
                    });
                }
```
